Question no.1 :-




Write a program that calculates and prints the value according to the given formula:




Q = Square root of [(2 * C * D)/H]




Following are the fixed values of C and H:




C is 50. H is 30.




D is the variable whose values should be input to your program in a comma-separated sequence.




Example




Let us assume the following comma separated input sequence is given to the program:




100,150,180




The output of the program should be:



18,22,24

Answer no.1

In [9]:
import math

c = 50
h = 30

value = []

D = input("Enter 3 values with commas:") 

items = [x for x in D.split(',')]

for D in items:

    value.append(str(int(round(math.sqrt(2*c*float(D)/h)))))


print("The followings output are:")

print(','.join(value))

Enter 3 values with commas:10,15,18
The followings output are:
6,7,8



Question no.2 :-

Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional array. The element value in the i-th row and j-th column of the array should be i*j.




Note: i=0,1.., X-1; j=0,1.., Y-1.




Example




Suppose the following inputs are given to the program:




3,5




Then, the output of the program should be:




[[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]]

Answer no.2

In [42]:
import numpy as np

A = np.fromfunction(lambda x,y:x*y,(3,5),dtype=int)

print(A)

[[0 0 0 0 0]
 [0 1 2 3 4]
 [0 2 4 6 8]]


Question no.3 :-

Write a program that accepts a comma separated sequence of words as input and prints the words in a comma-separated sequence after sorting them alphabetically.




Suppose the following input is supplied to the program:




without,hello,bag,world




Then, the output should be:



bag,hello,without,world

Answer no.3

In [49]:
words = input("Enter words with comma:")

W = words.split(",")

W.sort() 

print(",".join(W))

Enter words with comma:egg,omelette,fry,bhurji,mughlai
bhurji,egg,fry,mughlai,omelette


Question no.4 :-

Write a program that accepts a sequence of whitespace separated words as input and prints the words after removing all duplicate words and sorting them alphanumerically.




Suppose the following input is supplied to the program:




hello world and practice makes perfect and hello world again




Then, the output should be:



again and hello makes perfect practice world

Answer no.4

In [58]:
players = input("Enter words with space:")

P = players.split(" ")
S = list(set(P))
S.sort() 

print(" ".join(S))

Enter words with space:Sachin Sachin Sehwag Gambhir Dravid Dravid Ganguly Laxman Dravid
Dravid Gambhir Ganguly Laxman Sachin Sehwag


Question no.5 :-

Write a program that accepts a sentence and calculate the number of letters and digits.




Suppose the following input is supplied to the program:




hello world! 123




Then, the output should be:




LETTERS 10



DIGITS 3

Answer no.5

In [62]:
sen = input("Enter a sentence: ")
sen = list(sen)

w = 0
d = 0

for i in sen:
    if i.isalpha():
        w = w + 1
    elif i.isdigit():
        d = d + 1
    else:
        continue

print("Letters:", w)
print("Digits:", d)

Enter a sentence: RCB! will be the winner of IPL 2023
Letters: 23
Digits: 4


Question no.6 :-

A website requires the users to input username and password to register. Write a program to check the validity of password input by users.




Following are the criteria for checking the password:




1. At least 1 letter between [a-z]




2. At least 1 number between [0-9]




1. At least 1 letter between [A-Z]




3. At least 1 character from [$#@]




4. Minimum length of transaction password: 6




5. Maximum length of transaction password: 12




Your program should accept a sequence of comma separated passwords and will check them according to the above criteria. Passwords that match the criteria are to be printed, each separated by a comma.




Example




If the following passwords are given as input to the program:




ABd1234@1,a F1#,2w3E*,2We3345




Then, the output of the program should be:



ABd1234@1

Answer no.6

In [64]:
import re

passwords = input("Enter passwords with commas: ")
passwords = passwords.split(",")

approved = []
for i in passwords:
    
    if len(i) < 6 or len(i) > 12:
        continue

    elif not re.search("([a-z])+", i):
        continue

    elif not re.search("([A-Z])+", i):
        continue

    elif not re.search("([0-9])+", i):
        continue

    elif not re.search("([!@$%^&])+", i):
        continue

    else:
        approved.append(i)

print((",").join(approved))

Enter passwords with commas: CGc3421@3,b E4#,6v6G*,7Wx33319,7644@ddDx
CGc3421@3,7644@ddDx
