Question no.1 :- Write a Python program to Add Two Matrices?

Answer no.1

In [3]:
import numpy as np

A1 = [[9,7,3],

     [8,5,4],

     [2,8,8]]

  
A2 = [[1,6,5],

     [9,7,4],

     [4,2,4]]
 

Addition = np.array(A1) + np.array(A2)
print(Addition)

[[10 13  8]
 [17 12  8]
 [ 6 10 12]]


Question no.2 :- Write a Python program to Multiply Two Matrices?

Answer no.2

In [10]:
M1 = [[9,1,2],

      [7,7,6],

      [3,6,9]]

  
M2 = [[7,2,3],

      [5,5,7],

      [1,6,9]]
 

Multiplication = np.dot(M1,M2) 
print(Multiplication)

[[ 70  35  52]
 [ 90  85 124]
 [ 60  90 132]]


Question no.3 :- Write a Python program to Transpose a Matrix?

Answer no.3

In [16]:
Ar = [[1,2,3],

      [5,7,3],

      [3,6,7]]

B = np.array(Ar)
print(B.T)

[[1 5 3]
 [2 7 6]
 [3 3 7]]


Question no.4 :- Write a Python program to Sort Words in Alphabetic Order?

Answer no.4

In [24]:
sen = input("Enter a sentence: ")  
 
words = sen.split(" ")  
  
words.sort()
   
for word in words:  
   print(word,end = " ")

Enter a sentence: RCB will win IPL this time for the first time ever
IPL RCB ever first for the this time time will win 

Question no.5 :- Write a Python program to Remove Punctuation From a String?

Answer no.5

In [28]:
import string
 
My_string = "Will, RCB! Win: IPL: 2023?"
 
My_string = My_string.translate(str.maketrans('', '', string.punctuation))

print(My_string)

Will RCB Win IPL 2023
